apiVersion: v2
name: keycloak
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

  #appVersion: "26.3.3"

dependencies:
  - name: keycloak
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 25.2.0
