apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keycloak
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {}
  template:
    metadata:
      name: keycloak
    spec:
      project: admin
      source:
        repoURL: '{{ .metadata.annotations.adminRepoUrl }}'
        targetRevision: HEAD
        path: keycloak
        helm:
          parameters:
            - name: "keycloak.ingress.hostname"
              value: 'keycloak.{{ .metadata.annotations.baseUrl }}'
      destination:
        server: '{{ .server }}'
        namespace: keycloak
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - RespectIgnoreDifferences=true
          - ApplyOutOfSyncOnly=true
